# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 290608ac76ea5fe78b703c186cd71ac74f2c841c0bef871ef8c950eea8fd962d4c65b92f1e279b0461db73e2387daff6502fe02f29c8ca38abc1fe304e21f1ce

test:
  secret_key_base: 6d529a0b5ecb916cdbd7605abb12b85bc152cff0fc03d72ee6354d112a4b4e12241754f607990844586933944238636e2b466c77d6f7a21644e48be7a32c8676

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
